name: Custom CI

on: [push, pull_request]

jobs:
  default:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1    
    - name: npm install, and test
      run: |
        npm install
        npm test
        npm run cov
      env:
        CI: true
